config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"
  Sidekiq::Web.set :sessions, false
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resource :github, only: [] do
        post "/manual", to: "github#manual", as: "manual"
      end
    end
  end


  resources :github do
      post :repo, on: :collection
      delete :repo, on: :collection, to: "github#delete_repos"
      post :manual, on: :collection, to: "github#manual_commit", as: :manual
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth'}
  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:github]

  has_many :user_repos

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
        user.email = provider_data.info.email
        user.password = Devise.friendly_token[0, 20]
        user.token = provider_data.credentials.token
    end
  end

  def repo_ids
    user_repos.pluck(:repo_id)
  end

end

app/models/user_repo.rb
class UserRepo < ApplicationRecord
  belongs_to :user
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/api/v1/github_controller.rb
class Api::V1::GithubController < Api::V1::BaseController

  def manual
    if params[:token] == "batata_frita"
      begin
        AutoCommitForUsersJob.perform_later
        render_success
      rescue
        render_error
      end
    else
      render_error
    end
  end

  private

  def render_error
    render json: { errors: "Ooopsie!" },
      status: :unprocessable_entity
  end

  def render_success
    render json: { message: "All good!" },
      status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def repo
    GithubUpdaterService.new(current_user).create_repos(amount: params[:amount].to_i)
    redirect_to root_path
  end

  def delete_repos
    GithubUpdaterService.new(current_user).delete_all_repos
    redirect_to root_path
  end

  def manual_commit
    AutoCommitForUsersJob.perform_later
    redirect_to root_path
  end

end

app/controllers/omniauth_controller.rb
class OmniauthController <  Devise::OmniauthCallbacksController

  def github
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      flash[:error] = 'There was a problem signing you in. Please try again later'
      redirect_to root_path
    end
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please try again later'
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/github/repo.html.erb
<h1>Github#repo</h1>
<p>Find me in app/views/github/repo.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Githubber</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main-home" style=" background-image: url('<%= cl_image_path 'DeStijl' %>')">
  <div class="container">
    <% if user_signed_in? && current_user.user_repos.any? %>
      <%= link_to manual_github_index_path, method: :post do %>
        <%= cl_image_tag "git-commit", width: 200, height: 220, id: "logo-login" %>
      <div class="white-box">
        You have <%= current_user.user_repos.count %> repositories creating between 1 and 20 commits a day automatically. Click <%= link_to "here", repo_github_index_path, method: :delete %> to delete them.
      </div>
      <% end %>
    <% elsif user_signed_in? && current_user.user_repos.empty? %>
      <div class="white-box">
        <%= form_for :repo, url: repo_github_index_path, method: :post do |f| %>
        <%= select_tag(:amount, options_for_select([1, 2, 3]) ) %>
          <%= f.submit %>
        <% end %>
      </div>
    <% elsif !user_signed_in? %>
      <%- if devise_mapping.omniauthable? %>
        <%- User.omniauth_providers.each do |provider| %>
          <%= link_to omniauth_authorize_path(:user, provider) do  %>
            <%= cl_image_tag "github-logo", width: 200, height: 200, id: "logo-login" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div